before_all do
    ensure_git_status_clean
end

platform :ios do
    private_lane :update_version do
        UI.message "bumping minor"
        increment_version_number_in_plist(xcodeproj: './ios/ReactNativeFastlane.xcodeproj', bump_type: 'patch')
    end

    private_lane :staging_build do
        increment_build_number_in_plist(xcodeproj: './ios/ReactNativeFastlane.xcodeproj', target: 'ReactNativeFastlane')
        gym(scheme: 'ReactNativeFastlane-staging', workspace: './ios/ReactNativeFastlane.xcworkspace')
    end

    private_lane :release_build do
        increment_build_number_in_plist(xcodeproj: './ios/ReactNativeFastlane.xcodeproj', target: 'ReactNativeFastlane')
        gym(scheme: 'ReactNativeFastlane-release', workspace: './ios/ReactNativeFastlane.xcworkspace')
    end

    lane :beta do
        staging_build
        upload_to_testflight(username: 'youremail@gmail.com', app_identifier: 'ReactNativeFastlane')
        commit_version_bump(message: 'bump build')
        push_to_git_remote
    end

    lane :release do
        release_build
        deliver
        commit_version_bump(message: 'bump build')
        push_to_git_remote
    end
end

platform :android do
    desc "Android build and release to beta"
    lane :beta do
#         android_set_version_code(
#             version_code: number_of_commits,
#             gradle_file: "./android/app/build.gradle"
#         )
#         android_set_version_name(
#             version_name: "1.1.0",
#             gradle_file: "./android/app/build.gradle"
#         )
#         gradle(task: 'clean', project_dir: './android')
#         gradle(
#             task: 'bundle',
#             build_type: 'Release',
#             project_dir: './android',
#         )
        upload_to_play_store(
            track: 'internal',
            aab: './android/app/build/outputs/bundle/release/app-release.aab',
            json_key: './fastlane/play-store-credentials.json',
            release_status: 'draft'
        )
    end

    lane :release do
        increment_version_code(gradle_file_path: './android/app', app_folder_name: 'app')
        increment_version_name(app_project_dir: './android/app', bump_type: 'patch')
        gradle(task: 'clean', project_dir: './android/')
        gradle(task: 'bundle', build_type: 'Release', project_dir: './android')
        supply(track: 'production', aab: './android/app/build/outputs/bundle/release/app-release.aab', release_status: 'draft')
    end
end










































